[package]
name = "displayconfig"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
lto = true

[dependencies]
core-graphics = "0.23"
objc = "0.2"
objc-foundation = "0.1"
clap = { version = "4.5", features = ["derive"] }

[build-dependencies]
cc = "1.0"